### PR TITLE
support binary format of integers, e.g. 0b0101

### PR DESCRIPTION
**Pull request by p4l1ly**

### CODE REVIEW

**Comment by p4l1ly** [comment]
related to (but still not solving) the issue https://github.com/dtolnay/serde-yaml/issues/91

**Comment by p4l1ly** [comment]
btw any plans to use the yaml-rust's function Yaml::from_str? so that one would not have to implement these things twice?

**Comment by p4l1ly** [comment]
ok, now I see it is not in the core schema, but in the YAML tag repository, which is referenced in the section 10.4.

The `0b` format is however supported in some other yaml parsers, e.g. _pyyaml_. Maybe it could be a tiny reason for merging this?

**Comment by dtolnay** [comment]
@p4l1ly please add the email address in https://github.com/p4l1ly/serde-yaml/commit/63eabe420d66418de51ff0225b711b14915d8feb.patch to your GitHub account if you would like this commit attributed to you. https://github.com/settings/emails

**Pull request merged**
