### PR TITLE
128-bit integer support

### PR DESCRIPTION
**Pull request by asomers**
i128 and u128 can now be serialized and deserialized.  Support is conditionalized on the disabled-by-default `i128` feature flag, and requires rustc 1.26.0 or later.  The minimum required version of Serde is now 1.0.60.

### CODE REVIEW

**Comment by asomers** [comment]
Sigh, Travis seems to be skipping CI for the entire PR, not just that one commit.  I'll try to fix it.

**Comment by dtolnay** [comment]
What part of this makes it necessary to have an `i128` feature in Cargo.toml? Can you do it without a feature?

**Comment by asomers** [comment]
I could remove the feature.  The biggest downside I see is that consumers could accidentally write code that fails to compile with older compilers.  But if they're using `i128` anyway, then they already have that problem.

**Comment by dtolnay** [comment]
Users can *always* accidentally write code that fails to compile with older compilers, so I would prefer not to add a Cargo feature for that reason.

**Comment by asomers** [comment]
Ok, I'll remove it.  BTW, the main reason I used a feature was just because bincode did.  Though in bincode's case, the feature also pulls in another dependency.

**Comment by asomers** [comment]
Works for me.  `Value` is only used when you don't know the schema ahead of time, right?  In my case, I do.  As long as I can deserialize into a `u128`, I'm happy.

**Comment by dtolnay** [comment]
Correct. Deserializing into `u128` will support numbers up to 128 bits.

I published this change in 0.8.6.

**Pull request merged**
