### PR TITLE
Add methods to support multidoc deserialization

### PR DESCRIPTION
**Pull request by semtexzv**
Simply reorganizes creation of deserializer, and adds methods which correctly use the remaining state in multi-document inputs to deserialize these into Vecs.

Resolves https://github.com/dtolnay/serde-yaml/issues/175

### CODE REVIEW

**Comment by thedodd** [comment]
@semtexzv thanks for putting this PR together. I am currently using this branch in an application of mine and it works quite well. Any plans to add a `from_*_multidoc` for the slice & reader variants?

**Comment by de-vri-es** [comment]
This would be very useful to have. Is there anything still blocking this?

**Comment by semtexzv** [comment]
@dtolnay Ping

**Comment by jmfiaschi** [comment]
maybe @dtolnay can review ?

**Review by dtolnay — COMMENTED** [review]
Thanks for the PR. I think I would prefer not to expose it in this way. Having *n* new top-level functions to serve a relatively uncommon use case is not great, and additionally, assuming that the caller wants every document in the multidoc input deserialized as the same type T seems wrong.

I would consider something that follows more like serde_json's StreamDeserializer. There would only be 1 new top level type added, and each successive item deserialized from it is not necessarily the same type. For example they might even be dependent on each other, like if the yaml input consists of a header document that tells what type the remaining documents should be read as.

**Pull request closed without merging**
