### PR TITLE
 Support emitting spans when deserializing structures

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
Similar to https://github.com/alexcrichton/toml-rs/issues/236, https://github.com/serde-rs/json/issues/637, and https://github.com/serde-rs/serde/issues/1811, this provides a mechanism for extracting the source location for a particular value. I've mostly copied the `toml` crate's approach.

For more complex cases like mappings and sequences the spans don't look 100% correct (e.g. it may miss a closing `]` or mappings start at `: value` instead of `key: value`), but that may just be because of where `yaml_rust` decides to emit an event or because `yaml_rust::scanner::Marker` only records where an event starts and not its length.

In the long run I'd like to have a common mechanism/protocol for emitting span information in `serde` (outlined [here](https://github.com/Michael-F-Bryan/serde-spanned/blob/86e53c93ea30db5dae68c2862246c4cbe25a226f/RFC.md)), but in the meantime this should give us a good place to experiment.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
I've added some more tests and believe this is feature complete. @dtolnay, would you be able to review this PR?

There's a quirk when trying to get the start location of a map. For example, given this document...

```yml
document:
  first: 1
  second: 2
```

... and this struct definition...

```rust
#[derive(Debug, serde_derive::Deserialize)]
struct Document {
    nested: Spanned<Nested>,
}

#[derive(Debug, serde_derive::Deserialize)]
struct Nested {
   first: u32,
   second: u32,
}
```

... Our `Nested` item will seem to start at the colon *after* the `first` key instead of at the `f` character as one might expect.

I think this may have something to do with how maps are deserialized and when tokens are consumed, but I don't know how to resolve the issue cleanly. I wrote a doc-test so people are aware of this behaviour and to help detect when it is fixed in the future.

**Comment by Michael-F-Bryan** [comment]
@dtolnay other than making it compatible with Rust 1.31, is anything else blocking this PR from being merged?

**Comment by dccsillag** [comment]
This would be great to have!
Hope it gets merged.

**Review by dtolnay — COMMENTED** [review]
I'd prefer not to build this into serde_yaml. For now I would recommend using a different crate if you need the spans.

Thanks anyway for the PR!

**Comment by dccsillag** [comment]
Oh, I see. Thanks for your time :)

But is there even any YAML crate out there which supports this?

**Comment by Michael-F-Bryan** [comment]
> But is there even a YAML crate out there which supports this?

Not that I could find. Your best bet is to fork `serde_yaml` and implement it yourself.

**Pull request closed without merging**
